### ISSUE TITLE
Some dependencies missing

### ISSUE THREAD

**Issue by astroash** [ameliejyc/nativity#1]
Whilst github stalking I noticed I can't run your app. I _think_ this may be because you have some global dependencies which aren't locally listed in the `package.json`

Here's the errors I get when I try to ~~stalk~~ run.

## `npm i`:
<img width="671" alt="screen shot 2017-11-23 at 08 39 36" src="https://user-images.githubusercontent.com/14337958/33164349-3ba73a36-d02a-11e7-9df1-13f393c0171d.png">

## `npm start`:
<img width="674" alt="screen shot 2017-11-23 at 08 38 53" src="https://user-images.githubusercontent.com/14337958/33164354-45c28db8-d02a-11e7-8e10-194d60a2d48e.png">

**Comment by ameliejyc** [comment]
You total cutie! Thanks for bringing this to my attention. Try installing Watchman? That worked for me:

```
brew install watchman
```

If that doesn't work, try deleting your node modules and package-lock then npm installing again and then installing watchman.

```
rm -rf node_modules
rm -rf package-lock.json
```

Also install XCode first so that you can view the app in the iOS simulator when the npm start works. Let me know if that helps <3

**Comment by ameliejyc** [comment]
Also yeah, it comes up with some weird messages because I used create-react-native-app which is quite new and buggy and also I had to downgrade my npm to <v5 to initialise the app. But you shouldn't have to do that - the watchman install should fix it :)

**Comment by astroash** [comment]
Still can't get it working. I've:
- installed watchman (through npm)
- installed and opened xcode
- ran uninstalled node modules and reinstalled

Errors:
![xcodeerror](https://user-images.githubusercontent.com/14337958/33308214-698a565a-d411-11e7-8cff-c20d305891f7.gif)

**Comment by astroash** [comment]
Ignore me, I needed to edit my preferences..
<img width="825" alt="screen shot 2017-11-28 at 07 59 47" src="https://user-images.githubusercontent.com/14337958/33308514-ad20722c-d412-11e7-8a77-def5e1aa4047.png">

Works now :)

**Comment by ameliejyc** [comment]
YES! Xcode is drama, sorry you had to go through it. But now I can add all this useful info to the readme, thanks mate :hugs:
